using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SenacFlix.Infrastructure.Migrations
{
    public partial class SeedData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // =====================================================
            // 1. CLASSIFICACOES INDICATIVAS
            // =====================================================
            migrationBuilder.Sql(@"
                SET IDENTITY_INSERT ClassificacoesIndicativas ON;
                INSERT INTO ClassificacoesIndicativas (Id, Nome, IdadeMinima, Cor) VALUES 
                (1, 'Livre', 0, '#00A859'),
                (2, '10 Anos', 10, '#0072BC'),
                (3, '12 Anos', 12, '#FCC012'),
                (4, '14 Anos', 14, '#F78104'),
                (5, '16 Anos', 16, '#F00000'),
                (6, '18 Anos', 18, '#000000');
                SET IDENTITY_INSERT ClassificacoesIndicativas OFF;
            ");

            // =====================================================
            // 2. CATEGORIAS
            // =====================================================
            migrationBuilder.Sql(@"
                SET IDENTITY_INSERT Categorias ON;
                INSERT INTO Categorias (Id, Nome, Descricao, Ativo, DataCadastro) VALUES 
                (1, 'Ação', 'Filmes com muita adrenalina e explosões', 1, '2024-01-01'),
                (2, 'Comédia', 'Filmes para dar boas risadas', 1, '2024-01-01'),
                (3, 'Drama', 'Histórias emocionantes e profundas', 1, '2024-01-01'),
                (4, 'Ficção Científica', 'Filmes sobre o futuro e tecnologia', 1, '2024-01-01'),
                (5, 'Terror', 'Filmes assustadores', 1, '2024-01-01'),
                (6, 'Animação', 'Filmes animados para todas as idades', 1, '2024-01-01'),
                (7, 'Romance', 'Histórias de amor', 1, '2024-01-01'),
                (8, 'Documentário', 'Filmes baseados em fatos reais', 1, '2024-01-01');
                SET IDENTITY_INSERT Categorias OFF;
            ");

            // =====================================================
            // 3. ASP.NET IDENTITY (ROLES E USUÁRIOS)
            // =====================================================
            migrationBuilder.Sql(@"
                -- Tabela de Perfis (Roles)
                INSERT INTO Identidade_Perfis (Id, Name, NormalizedName) VALUES 
                ('11111111-1111-1111-1111-111111111111', 'Admin', 'ADMIN'),
                ('22222222-2222-2222-2222-222222222222', 'Operador', 'OPERADOR'),
                ('33333333-3333-3333-3333-333333333333', 'Cliente', 'CLIENTE');

                -- Tabela de Usuários (Users)
                -- A senha 'Senac@123' foi pré-hasheada para manter a idempotência da Migration
                INSERT INTO Identidade_Usuarios (
                    Id, UserName, NormalizedUserName, Email, NormalizedEmail, EmailConfirmed, 
                    PasswordHash, SecurityStamp, ConcurrencyStamp, NomeCompleto, DataNascimento,
                    FotoPerfilUrl, Ativo, DataCadastro, DataAtualizacao,
                    PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, AccessFailedCount
                ) VALUES 
                ('44444444-4444-4444-4444-444444444444', 'admin@senacflix.com', 'ADMIN@SENACFLIX.COM', 'admin@senacflix.com', 'ADMIN@SENACFLIX.COM', 1, 'AQAAAAIAAYagAAAAEFPAff20kAVxHhe6nfH7pejAz6B51YDAUgLqR8kWyfwtWtftugiuD3NUbYnLMeTx2w==', '214f3e20-cff3-4007-8c17-54ffa371eff2', '2ae3dc3b-2c48-4853-91a2-ed53ce464f95', 'Administrador SenacFlix', '2000-01-01', NULL, 1, '2024-01-01', NULL, 0, 0, 0, 0),
                ('55555555-5555-5555-5555-555555555555', 'operador@senacflix.com', 'OPERADOR@SENACFLIX.COM', 'operador@senacflix.com', 'OPERADOR@SENACFLIX.COM', 1, 'AQAAAAIAAYagAAAAEClCAlDmfL9zFefdnM+/fso0Vcjn5/Xnmis9yns0etugyBgLRhtzfD0GUUPWM+tTQQ==', '8ebab07b-e926-4a54-980d-dd3823968a6a', '80fa85e9-7e51-4c6c-8e20-ab61439afff2', 'Operador SenacFlix', '2000-01-01', NULL, 1, '2024-01-01', NULL, 0, 0, 0, 0),
                ('66666666-6666-6666-6666-666666666666', 'cliente@senacflix.com', 'CLIENTE@SENACFLIX.COM', 'cliente@senacflix.com', 'CLIENTE@SENACFLIX.COM', 1, 'AQAAAAIAAYagAAAAEHAjgGf6kv5bcO3/4d67SIwffT9W4yr37SmuhFkhSqVAvTizYA7jFXLlL1vNXcQbMQ==', 'd063d964-006b-48df-bb83-3db7d45e9e21', 'd8d37e60-f9b1-47b3-b6a3-71c5de02b261', 'Cliente SenacFlix', '2000-01-01', NULL, 1, '2024-01-01', NULL, 0, 0, 0, 0);

                -- Vinculando Usuários aos Perfis
                INSERT INTO Identidade_UsuarioPerfis (UserId, RoleId) VALUES 
                ('44444444-4444-4444-4444-444444444444', '11111111-1111-1111-1111-111111111111'),
                ('55555555-5555-5555-5555-555555555555', '22222222-2222-2222-2222-222222222222'),
                ('66666666-6666-6666-6666-666666666666', '33333333-3333-3333-3333-333333333333');
            ");

            // =====================================================
            // 4. FILMES
            // =====================================================
            migrationBuilder.Sql(@"
                SET IDENTITY_INSERT Filmes ON;

                INSERT INTO Filmes 
                (
                    Id, Titulo, AnoLancamento, Duracao, Descricao, Diretor, Elenco, 
                    ImagemCapaUrl, ImagemBannerUrl, TrailerYoutubeUrl, VideoYoutubeUrl, 
                    CategoriaId, ClassificacaoIndicativaId, Ativo, DestaqueHome, DataCadastro
                )
                VALUES
                    (1, N'Interestelar', 2014, 169, N'Um grupo de exploradores faz uso de um buraco de minhoca recém-descoberto para superar as limitações das viagens espaciais humanas e conquistar as vastidões do universo.', N'Christopher Nolan', N'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine', N'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', N'https://image.tmdb.org/t/p/w1280/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg', N'https://www.youtube.com/embed/zSWdZVtXT7E', N'https://www.youtube.com/embed/zSWdZVtXT7E', 4, 3, 1, 0, '2024-01-01'),
                    (2, N'Oppenheimer', 2023, 180, N'A história do físico J. Robert Oppenheimer e sua função no Projeto Manhattan, que levou ao desenvolvimento das primeiras armas nucleares durante a Segunda Guerra Mundial.', N'Christopher Nolan', N'Cillian Murphy, Emily Blunt, Robert Downey Jr., Matt Damon', N'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', N'https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg', N'https://www.youtube.com/embed/uYPbbksJxIg', N'https://www.youtube.com/embed/uYPbbksJxIg', 3, 4, 1, 0, '2024-01-01'),
                    (3, N'Duna', 2021, 155, N'O jovem Paul Atreides, filho de uma família nobre, chega ao planeta mais perigoso do universo para garantir o futuro de sua família e de seu povo. Mas antes disso, terá que superar seus próprios medos.', N'Denis Villeneuve', N'Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Zendaya', N'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV48Ziti0dkx.jpg', N'https://image.tmdb.org/t/p/w1280/iopYFB1b6Bh7FWZh3onQhph1sih.jpg', N'https://www.youtube.com/embed/8g18jFHCLXk', N'https://www.youtube.com/embed/8g18jFHCLXk', 4, 3, 1, 0, '2024-01-01'),
                    (4, N'Duna: Parte Dois', 2024, 166, N'Paul Atreides se une a Chani e aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família. Diante de uma escolha entre o amor de sua vida e o destino do universo, ele se esforça para evitar um futuro aterrorizante.', N'Denis Villeneuve', N'Timothée Chalamet, Zendaya, Rebecca Ferguson, Austin Butler', N'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', N'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg', N'https://www.youtube.com/embed/Way9Dexny3w', N'https://www.youtube.com/embed/Way9Dexny3w', 4, 4, 1, 0, '2024-01-01'),
                    (5, N'Batman Begins', 2005, 140, N'Após treinar com seu mentor, Bruce Wayne retorna para Gotham City e começa a combater os criminosos que destruíram sua vida como o vigilante mascarado Batman.', N'Christopher Nolan', N'Christian Bale, Michael Caine, Liam Neeson, Katie Holmes', N'https://image.tmdb.org/t/p/w500/8RW2runSEc34IwKN2D1aPcJd2UL.jpg', N'https://image.tmdb.org/t/p/w1280/uBtwS8hJ64LS8BBaiKHzcxsdrLs.jpg', N'https://www.youtube.com/embed/neY2xVmOfUM', N'https://www.youtube.com/embed/neY2xVmOfUM', 1, 3, 1, 0, '2024-01-01'),
                    (6, N'O Cavaleiro das Trevas', 2008, 152, N'Quando o Coringa mergulha Gotham City no caos, Batman deve aceitar uma das maiores provas psicológicas de sua capacidade de combater a injustiça.', N'Christopher Nolan', N'Christian Bale, Heath Ledger, Aaron Eckhart, Maggie Gyllenhaal', N'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', N'https://image.tmdb.org/t/p/w1280/hqkIcbrOHL86UncnHIsHVcVmzue.jpg', N'https://www.youtube.com/embed/EXeTwQWrcwY', N'https://www.youtube.com/embed/EXeTwQWrcwY', 1, 3, 1, 0, '2024-01-01'),
                    (7, N'Coringa', 2019, 122, N'Em Gotham City, o comediante fracassado Arthur Fleck é desrespeitado e ignorado pela sociedade. Ele então embarca em uma jornada descendente para a loucura e se torna o Coringa.', N'Todd Phillips', N'Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy', N'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', N'https://image.tmdb.org/t/p/w1280/f5F4cRhQdUbyVbB5lTNCwFMTDoa.jpg', N'https://www.youtube.com/embed/zAGVQLHvwOY', N'https://www.youtube.com/embed/zAGVQLHvwOY', 3, 5, 1, 0, '2024-01-01'),
                    (8, N'Avatar', 2009, 162, N'Um ex-fuzileiro naval paraplégico é enviado para a lua Pandora em missão diplomática. Dividido entre suas ordens e o amor por seu novo lar, ele deve liderar uma batalha épica pelo destino de um mundo.', N'James Cameron', N'Sam Worthington, Zoe Saldana, Sigourney Weaver, Michelle Rodriguez', N'https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg', N'https://image.tmdb.org/t/p/w1280/s16H6tpK2utvwpapmrhDo0U3yoD.jpg', N'https://www.youtube.com/embed/5PSNL1qE6VY', N'https://www.youtube.com/embed/5PSNL1qE6VY', 4, 3, 1, 0, '2024-01-01'),
                    (9, N'Avatar: O Caminho da Água', 2022, 192, N'Jake Sully vive com sua nova família em Pandora. Quando uma antiga ameaça retorna para terminar o que havia começado, Jake deve trabalhar com Neytiri e o exército dos Na''vi para proteger seu planeta.', N'James Cameron', N'Sam Worthington, Zoe Saldana, Sigourney Weaver, Kate Winslet', N'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg', N'https://image.tmdb.org/t/p/w1280/4SzT8EZr3WyWrBLimJMH7K7VFZZ.jpg', N'https://www.youtube.com/embed/d9MyW72ELq0', N'https://www.youtube.com/embed/d9MyW72ELq0', 4, 3, 1, 0, '2024-01-01'),
                    (10, N'Vingadores: Ultimato', 2019, 181, N'Após os eventos devastadores de Vingadores: Guerra Infinita, o universo está em ruínas. Com a ajuda de aliados restantes, os Vingadores se reúnem mais uma vez para reverter as ações de Thanos e restaurar o equilíbrio no universo.', N'Anthony Russo, Joe Russo', N'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth', N'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg', N'https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg', N'https://www.youtube.com/embed/TcMBFSGVi1c', N'https://www.youtube.com/embed/TcMBFSGVi1c', 1, 3, 1, 0, '2024-01-01'),
                    (11, N'Homem de Ferro', 2008, 126, N'Tony Stark, um gênio milionário e fabricante de armas, é capturado por terroristas e forçado a construir uma arma de destruição. Em vez disso, constrói uma armadura de alta tecnologia e a usa para escapar e tornar-se o Homem de Ferro.', N'Jon Favreau', N'Robert Downey Jr., Gwyneth Paltrow, Jeff Bridges, Terrence Howard', N'https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBF8l6T0qg.jpg', N'https://image.tmdb.org/t/p/w1280/cyecB7godJ6kNHGONFjUyVN9OX5.jpg', N'https://www.youtube.com/embed/8ugaeA-nMTc', N'https://www.youtube.com/embed/8ugaeA-nMTc', 1, 3, 1, 0, '2024-01-01'),
                    (12, N'Doutor Estranho', 2016, 115, N'O Dr. Stephen Strange, um neurocirurgião de elite, descobre o mundo oculto da magia e dimensões alternativas depois de um acidente de carro que arruinou sua carreira.', N'Scott Derrickson', N'Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Tilda Swinton', N'https://image.tmdb.org/t/p/w500/uGBVl7yu7QoD5Vc3N47Zft9BQFN.jpg', N'https://image.tmdb.org/t/p/w1280/hbhFnRzzg6ZDmm8YAmxBnmtM9S5.jpg', N'https://www.youtube.com/embed/HSzx-zryEgM', N'https://www.youtube.com/embed/HSzx-zryEgM', 1, 3, 1, 0, '2024-01-01'),
                    (13, N'Top Gun: Maverick', 2022, 130, N'Depois de mais de 30 anos de serviço como um dos melhores aviadores da Marinha, Pete ''Maverick'' Mitchell está de volta como treinador de uma nova geração de pilotos.', N'Joseph Kosinski', N'Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm', N'https://image.tmdb.org/t/p/w500/62HCnUTHjWTObPnSPIOnczjmf5P.jpg', N'https://image.tmdb.org/t/p/w1280/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg', N'https://www.youtube.com/embed/qSqVVswa420', N'https://www.youtube.com/embed/qSqVVswa420', 1, 3, 1, 0, '2024-01-01'),
                    (14, N'John Wick', 2014, 101, N'Um ex-assassino sai da aposentadoria para procurar os gangsters que roubaram seu carro e mataram seu cachorro, um presente de seu amor falecido.', N'Chad Stahelski', N'Keanu Reeves, Michael Nyqvist, Alfie Allen, Adrianne Palicki', N'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg', N'https://image.tmdb.org/t/p/w1280/mMtUybQ6hL24FXo0F3Z4j2KG7kQ.jpg', N'https://www.youtube.com/embed/2AUmvWm5ZDQ', N'https://www.youtube.com/embed/2AUmvWm5ZDQ', 1, 5, 1, 0, '2024-01-01'),
                    (15, N'Parasita', 2019, 132, N'A família Ki-taek vive em situação de pobreza extrema em uma casa semi-subterrânea. Quando o filho mais velho consegue emprego de tutor na família rica Park, os Ki-taek passam a infiltrar-se cada vez mais na vida dos empregadores.', N'Bong Joon-ho', N'Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo, Woo-sik Choi', N'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', N'https://image.tmdb.org/t/p/w1280/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg', N'https://www.youtube.com/embed/5xH0HfJHsaY', N'https://www.youtube.com/embed/5xH0HfJHsaY', 5, 5, 1, 0, '2024-01-01'),
                    (16, N'A Origem', 2010, 148, N'Um ladrão especialista em invadir os sonhos das pessoas para extrair informações valiosas de seu subconsciente recebe uma missão inversa: plantar uma ideia na mente de um CEO.', N'Christopher Nolan', N'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy', N'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', N'https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg', N'https://www.youtube.com/embed/YoHD9XEInc0', N'https://www.youtube.com/embed/YoHD9XEInc0', 4, 3, 1, 0, '2024-01-01'),
                    (17, N'O Poderoso Chefão', 1972, 175, N'O patriarca envelhecido de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.', N'Francis Ford Coppola', N'Marlon Brando, Al Pacino, James Caan, Richard Castellano', N'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLegHnDmni4v.jpg', N'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg', N'https://www.youtube.com/embed/sY1S34973zA', N'https://www.youtube.com/embed/sY1S34973zA', 3, 5, 1, 0, '2024-01-01'),
                    (18, N'Clube da Luta', 1999, 139, N'Um narrador insone e um fabricante de sabão criam um clube de luta subterrâneo que evolui para algo muito mais perturbador.', N'David Fincher', N'Brad Pitt, Edward Norton, Helena Bonham Carter, Meat Loaf', N'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', N'https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg', N'https://www.youtube.com/embed/qtRKdVHc-cE', N'https://www.youtube.com/embed/qtRKdVHc-cE', 3, 6, 1, 0, '2024-01-01'),
                    (19, N'Forrest Gump', 1994, 142, N'A presidência de vários presidentes, a guerra do Vietnã, o movimento pelos direitos civis e outros eventos históricos do século XX se desdobram através da perspectiva de um homem do Alabama com QI abaixo da média.', N'Robert Zemeckis', N'Tom Hanks, Robin Wright, Gary Sinise, Sally Field', N'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', N'https://image.tmdb.org/t/p/w1280/qdIMHd4sEfJSckfVJfKQvisL02a.jpg', N'https://www.youtube.com/embed/bLvqoHBptjg', N'https://www.youtube.com/embed/bLvqoHBptjg', 3, 3, 1, 0, '2024-01-01'),
                    (20, N'Matrix', 1999, 136, N'Um hacker descobre que toda a realidade que conhece é uma simulação criada por máquinas, e se junta a um grupo de rebeldes para lutar contra elas.', N'Lilly Wachowski, Lana Wachowski', N'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving', N'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', N'https://image.tmdb.org/t/p/w1280/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg', N'https://www.youtube.com/embed/m8e-FF8MsqU', N'https://www.youtube.com/embed/m8e-FF8MsqU', 4, 4, 1, 0, '2024-01-01'),
                    (21, N'O Senhor dos Anéis: A Sociedade do Anel', 2001, 178, N'Um jovem hobbit chamado Frodo Bolseiro herda um anel misterioso que pode ser a chave para a dominação de toda a Terra Média pela força das trevas. Ele parte em uma jornada épica acompanhado por uma sociedade de companheiros.', N'Peter Jackson', N'Elijah Wood, Ian McKellen, Orlando Bloom, Sean Connery', N'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', N'https://image.tmdb.org/t/p/w1280/pIgMoFPGCMJ9axUJDaHDw0tB86m.jpg', N'https://www.youtube.com/embed/V75dMMIW2B4', N'https://www.youtube.com/embed/V75dMMIW2B4', 1, 3, 1, 0, '2024-01-01'),
                    (22, N'O Senhor dos Anéis: O Retorno do Rei', 2003, 201, N'A batalha final pelo destino da Terra Média se aproxima. Frodo e Samwise avançam em direção à Montanha da Perdição enquanto o Exército do Bem faz o último confronto contra as forças de Sauron.', N'Peter Jackson', N'Elijah Wood, Viggo Mortensen, Ian McKellen, Orlando Bloom', N'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', N'https://image.tmdb.org/t/p/w1280/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg', N'https://www.youtube.com/embed/r5X-hFf6Bwo', N'https://www.youtube.com/embed/r5X-hFf6Bwo', 1, 3, 1, 0, '2024-01-01'),
                    (23, N'Star Wars: O Despertar da Força', 2015, 138, N'Três décadas após o Império, uma nova ameaça surge: a Primeira Ordem. Com a ajuda de uma jovem destemida, um ex-soldado e um velho amigo, os Rebeldes confrontam os novos vilões.', N'J.J. Abrams', N'Harrison Ford, Mark Hamill, Carrie Fisher, Adam Driver', N'https://image.tmdb.org/t/p/w500/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg', N'https://image.tmdb.org/t/p/w1280/c2Ax8Rox5g6CneChwy1idykaZdO.jpg', N'https://www.youtube.com/embed/sGbxmsDFVnE', N'https://www.youtube.com/embed/sGbxmsDFVnE', 4, 2, 1, 0, '2024-01-01'),
                    (24, N'Homem-Aranha: Sem Volta para Casa', 2021, 148, N'Peter Parker pede ao Doutor Estranho que o mundo esqueça que ele é o Homem-Aranha. O feitiço atrai super-vilões de universos paralelos para o seu mundo.', N'Jon Watts', N'Tom Holland, Zendaya, Benedict Cumberbatch, Willem Dafoe', N'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', N'https://image.tmdb.org/t/p/w1280/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg', N'https://www.youtube.com/embed/JfVOs4VSpmA', N'https://www.youtube.com/embed/JfVOs4VSpmA', 1, 3, 1, 0, '2024-01-01'),
                    (25, N'Guardiões da Galáxia', 2014, 121, N'Um grupo improvável de anti-heróis se une para proteger uma esfera muito poderosa das garras do fanático Ronan, um vilão que ameaça o equilíbrio do universo.', N'James Gunn', N'Chris Pratt, Vin Diesel, Bradley Cooper, Zoe Saldana', N'https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg', N'https://image.tmdb.org/t/p/w1280/bHarw68REr6IURV0b4bOyveDdOH.jpg', N'https://www.youtube.com/embed/d96cjJhvlMA', N'https://www.youtube.com/embed/d96cjJhvlMA', 4, 3, 1, 0, '2024-01-01'),
                    (26, N'Thor: Ragnarok', 2017, 130, N'Thor é aprisionado no outro lado do universo. Para salvar Asgard de Hela, a deusa da morte, ele precisa lutar numa arena e vencer o Incrível Hulk.', N'Taika Waititi', N'Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Idris Elba', N'https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2znIiWMt8Wx.jpg', N'https://image.tmdb.org/t/p/w1280/kaIfm5ryEOwmOqJYoMnWMQv40t5.jpg', N'https://www.youtube.com/embed/ue80QwXMRHg', N'https://www.youtube.com/embed/ue80QwXMRHg', 1, 3, 1, 0, '2024-01-01'),
                    (27, N'Pantera Negra', 2018, 134, N'T''Challa retorna à nação africana de Wakanda para assumir o trono. Mas quando um inimigo do passado surge para desafiar seu poder, o Rei guerreiro se vê em um conflito que coloca todo o destino de Wakanda em risco.', N'Ryan Coogler', N'Chadwick Boseman, Michael B. Jordan, Lupita Nyong''o, Danai Gurira', N'https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg', N'https://image.tmdb.org/t/p/w1280/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg', N'https://www.youtube.com/embed/xjDjIWPwcPU', N'https://www.youtube.com/embed/xjDjIWPwcPU', 1, 3, 1, 0, '2024-01-01'),
                    (28, N'Tenet', 2020, 150, N'Um agente secreto aprende a manipular o fluxo do tempo e usa essa habilidade para evitar a Terceira Guerra Mundial.', N'Christopher Nolan', N'John David Washington, Robert Pattinson, Elizabeth Debicki, Kenneth Branagh', N'https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijWhGb.jpg', N'https://image.tmdb.org/t/p/w1280/wzJRB4MKi3yK138bpyqA2E2HIXR.jpg', N'https://www.youtube.com/embed/LdOM0x0XDMo', N'https://www.youtube.com/embed/LdOM0x0XDMo', 4, 3, 1, 0, '2024-01-01'),
                    (29, N'Dunkirk', 2017, 106, N'Soldados aliados britânicos, belgas, canadenses e franceses são cercados por forças alemãs e evacuados durante uma batalha decisiva da Segunda Guerra Mundial.', N'Christopher Nolan', N'Fionn Whitehead, Tom Glynn-Carney, Jack Lowden, Harry Styles', N'https://image.tmdb.org/t/p/w500/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg', N'https://image.tmdb.org/t/p/w1280/fudEG8VHJJEPi7QSBOQZ9j8WXsG.jpg', N'https://www.youtube.com/embed/F-eMt3SrfFU', N'https://www.youtube.com/embed/F-eMt3SrfFU', 3, 3, 1, 0, '2024-01-01'),
                    (30, N'1917', 2019, 119, N'April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.', N'Sam Mendes', N'George MacKay, Dean-Charles Chapman, Mark Strong, Andrew Scott', N'https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg', N'https://image.tmdb.org/t/p/w1280/yrFR7M2HpPb5oFpkqNz8FmXSS7e.jpg', N'https://www.youtube.com/embed/YqNYrYUiMfg', N'https://www.youtube.com/embed/YqNYrYUiMfg', 3, 4, 1, 0, '2024-01-01'),
                    (31, N'Mad Max: Estrada da Fúria', 2015, 120, N'Em um mundo apocalíptico, o solitário Max se junta à imperatriz Furiosa para escapar do tirano Immortan Joe. Uma perseguição brutal no deserto que beira o impossível.', N'George Miller', N'Tom Hardy, Charlize Theron, Nicholas Hoult, Hugh Keays-Byrne', N'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg', N'https://image.tmdb.org/t/p/w1280/phszHPFnhRUMhHHMoOgPtKRNiKz.jpg', N'https://www.youtube.com/embed/hEJnMQG9ev8', N'https://www.youtube.com/embed/hEJnMQG9ev8', 1, 5, 1, 0, '2024-01-01'),
                    (32, N'Gravity', 2013, 91, N'Uma engenheira médica em sua primeira missão espacial é lançada ao espaço profundo após um acidente. Ela deve sobreviver e encontrar seu caminho de volta à Terra.', N'Alfonso Cuarón', N'Sandra Bullock, George Clooney, Ed Harris, Orto Ignatiussen', N'https://image.tmdb.org/t/p/w500/iJBraj7Nkl4RqBgguRQBz1VKXKM.jpg', N'https://image.tmdb.org/t/p/w1280/hGFGOdSRBP4EQniRMFOCGBlSX6N.jpg', N'https://www.youtube.com/embed/OiTiKOy59o4', N'https://www.youtube.com/embed/OiTiKOy59o4', 4, 3, 1, 0, '2024-01-01'),
                    (33, N'The Revenant: O Renascido', 2015, 156, N'Um explorador, atacado e deixado para morrer por seu guia, busca sobrevivência e vingança no selvagem oeste americano do século XIX.', N'Alejandro G. Iñárritu', N'Leonardo DiCaprio, Tom Hardy, Will Poulter, Domhnall Gleeson', N'https://image.tmdb.org/t/p/w500/ji3ecJphATlVgq9BBk1J7L1YgwS.jpg', N'https://image.tmdb.org/t/p/w1280/lijwRHkGrCbNQdS8kGXxDqJHAjx.jpg', N'https://www.youtube.com/embed/LoebZZ8K5N0', N'https://www.youtube.com/embed/LoebZZ8K5N0', 3, 5, 1, 0, '2024-01-01'),
                    (34, N'Bohemian Rhapsody', 2018, 134, N'A história de Freddie Mercury, o lendário vocalista do Queen, desde a formação da banda até a lendária apresentação no Live Aid em 1985.', N'Bryan Singer', N'Rami Malek, Lucy Boynton, Gwilym Lee, Ben Hardy', N'https://image.tmdb.org/t/p/w500/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg', N'https://image.tmdb.org/t/p/w1280/3vZDHryGCbOqgLh1Y5NcNY7OQVP.jpg', N'https://www.youtube.com/embed/mP0VHJYFOAU', N'https://www.youtube.com/embed/mP0VHJYFOAU', 3, 3, 1, 0, '2024-01-01'),
                    (35, N'Whiplash', 2014, 107, N'Um jovem baterista ambicioso frequenta o melhor conservatório de música do país, onde é orientado por um dos regentes mais temidos do país.', N'Damien Chazelle', N'Miles Teller, J.K. Simmons, Melissa Benoist, Paul Reiser', N'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg', N'https://image.tmdb.org/t/p/w1280/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg', N'https://www.youtube.com/embed/7d_jQycdQGo', N'https://www.youtube.com/embed/7d_jQycdQGo', 3, 4, 1, 0, '2024-01-01'),
                    (36, N'La La Land', 2016, 128, N'Enquanto Los Angeles vivencia outra bela estação, um ator e uma pianista de jazz se apaixonam ao mesmo tempo que buscam seus sonhos e lutam para achar um lugar em um mundo que raramente os acolhe.', N'Damien Chazelle', N'Ryan Gosling, Emma Stone, John Legend, Rosemarie DeWitt', N'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg', N'https://image.tmdb.org/t/p/w1280/nadTlnTE6DdgmYsN4iWb4gHwpDj.jpg', N'https://www.youtube.com/embed/0pdqf4P9MB8', N'https://www.youtube.com/embed/0pdqf4P9MB8', 2, 2, 1, 0, '2024-01-01'),
                    (37, N'O Lobo de Wall Street', 2013, 180, N'Baseado na história real de Jordan Belfort, desde sua ascensão no mercado financeiro de Nova York até sua queda após um esquema de corrupção e crime organizado.', N'Martin Scorsese', N'Leonardo DiCaprio, Jonah Hill, Margot Robbie, Kyle Chandler', N'https://image.tmdb.org/t/p/w500/pWHf4khOloNVfCxscsXFj3jj6gP.jpg', N'https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg', N'https://www.youtube.com/embed/iszwuX1AK6A', N'https://www.youtube.com/embed/iszwuX1AK6A', 3, 6, 1, 0, '2024-01-01'),
                    (38, N'Django Livre', 2012, 165, N'Com a ajuda de um caçador de recompensas alemão, um escravo recém-liberto percorre o sul dos Estados Unidos para resgatar sua esposa de um proprietário de plantação brutal.', N'Quentin Tarantino', N'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington', N'https://image.tmdb.org/t/p/w500/5WJnGM9GKgMqXkd2PeWxnBtjfqO.jpg', N'https://image.tmdb.org/t/p/w1280/7Lh5R7tBpyGDPBDKHWxqlJbgFN.jpg', N'https://www.youtube.com/embed/eUdM9vrCbow', N'https://www.youtube.com/embed/eUdM9vrCbow', 1, 5, 1, 0, '2024-01-01'),
                    (39, N'Bastardos Inglórios', 2009, 153, N'Na França ocupada pelos nazistas durante a Segunda Guerra Mundial, o Tenente Aldo Raine organiza um grupo de soldados judeus para cometer atos violentos de vingança contra os nazistas.', N'Quentin Tarantino', N'Brad Pitt, Christoph Waltz, Michael Fassbender, Eli Roth', N'https://image.tmdb.org/t/p/w500/vDwqPyhkzFPRDmwz9KbTN5jFxm3.jpg', N'https://image.tmdb.org/t/p/w1280/7cBaQbBrFZJjfQKvdV3iy6Q9kxR.jpg', N'https://www.youtube.com/embed/KnrRy6kSFFU', N'https://www.youtube.com/embed/KnrRy6kSFFU', 3, 5, 1, 0, '2024-01-01'),
                    (40, N'Era Uma Vez em Hollywood', 2019, 161, N'Um ator e seu dublê navegam pelo mundo de Hollywood em seus últimos anos de glória durante o verão de 1969 em Los Angeles.', N'Quentin Tarantino', N'Leonardo DiCaprio, Brad Pitt, Margot Robbie, Emile Hirsch', N'https://image.tmdb.org/t/p/w500/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg', N'https://image.tmdb.org/t/p/w1280/aI7J7OP3EPbXBjAHnq8H5Sld71x.jpg', N'https://www.youtube.com/embed/ELeMaP8EPAA', N'https://www.youtube.com/embed/ELeMaP8EPAA', 3, 5, 1, 0, '2024-01-01'),
                    (41, N'Jurassic World', 2015, 124, N'Um novo parque temático de dinossauros é inaugurado com sucesso. Mas quando um dinossauro geneticamente modificado escapa, o caos se instala e a sobrevivência humana fica em xeque.', N'Colin Trevorrow', N'Chris Pratt, Bryce Dallas Howard, Nick Robinson, Ty Simpkins', N'https://image.tmdb.org/t/p/w500/dkMD5qe2QiAMGhCrOFNnF3M5TGF.jpg', N'https://image.tmdb.org/t/p/w1280/bqlJDTOtXDRHpMhOMDiGOSFNzl3.jpg', N'https://www.youtube.com/embed/RFinNxS5KN4', N'https://www.youtube.com/embed/RFinNxS5KN4', 1, 3, 1, 0, '2024-01-01'),
                    (42, N'Titanic', 1997, 194, N'Uma jovem de família nobre se apaixona por um artista humilde a bordo do navio mais famoso da história, o Titanic, cujo destino trágico já conhecemos.', N'James Cameron', N'Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates', N'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', N'https://image.tmdb.org/t/p/w1280/kHXEpyfl6zqn8a6YuozZUujufXf.jpg', N'https://www.youtube.com/embed/kVrqfYjkTdQ', N'https://www.youtube.com/embed/kVrqfYjkTdQ', 3, 3, 1, 0, '2024-01-01'),
                    (43, N'De Volta para o Futuro', 1985, 116, N'Marty McFly é acidentalmente enviado de volta para 1955 em um carro-máquina do tempo DeLorean. Ele deve garantir que seus pais se apaixonem e encontrar uma maneira de voltar para o futuro.', N'Robert Zemeckis', N'Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover', N'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg', N'https://image.tmdb.org/t/p/w1280/dziRPFmCFRHKDFcOJLjfIOOXSKO.jpg', N'https://www.youtube.com/embed/qvsgGtivCgs', N'https://www.youtube.com/embed/qvsgGtivCgs', 4, 1, 1, 0, '2024-01-01'),
                    (44, N'Gladiador', 2000, 155, N'Um general romano traído e escravizado busca vingança contra o corrupto imperador que assassinou sua família. Sua jornada o transforma em um gladiador implacável.', N'Ridley Scott', N'Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed', N'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg', N'https://image.tmdb.org/t/p/w1280/6WBIzCgmDCYrqh64yDREGeDk9d3.jpg', N'https://www.youtube.com/embed/P5ieIbInFpg', N'https://www.youtube.com/embed/P5ieIbInFpg', 1, 5, 1, 0, '2024-01-01'),
                    (45, N'Missão: Impossível — Protocolo Fantasma', 2011, 133, N'O agente Ethan Hunt e sua equipe são responsabilizados por um atentado ao Kremlin. Para limpar o nome da IMF, eles devem agir sozinhos e impedir uma guerra nuclear.', N'Brad Bird', N'Tom Cruise, Jeremy Renner, Simon Pegg, Paula Patton', N'https://image.tmdb.org/t/p/w500/s1cxSaH8gFuXGGFyFVNOhlXaHkv.jpg', N'https://image.tmdb.org/t/p/w1280/g3jLiGLCVVkiHFbtAl8NQHuJiMB.jpg', N'https://www.youtube.com/embed/I4sqAuzpB-w', N'https://www.youtube.com/embed/I4sqAuzpB-w', 1, 3, 1, 0, '2024-01-01'),
                    (46, N'Capitã Marvel', 2019, 124, N'Carol Danvers se torna uma das heroínas mais poderosas do universo enquanto a Terra é apanhada no meio de uma guerra galáctica entre duas raças alienígenas.', N'Anna Boden, Ryan Fleck', N'Brie Larson, Samuel L. Jackson, Ben Mendelsohn, Jude Law', N'https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg', N'https://image.tmdb.org/t/p/w1280/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg', N'https://www.youtube.com/embed/Z1BCujX3pw8', N'https://www.youtube.com/embed/Z1BCujX3pw8', 1, 3, 1, 0, '2024-01-01'),
                    (47, N'Rápidos e Furiosos 7', 2015, 137, N'Deckard Shaw busca vingança pelo irmão contra Dominic Toretto e sua equipe enquanto um misterioso mercenário usa a equipe como peões em sua missão de matar um hacker.', N'James Wan', N'Vin Diesel, Paul Walker, Dwayne Johnson, Jason Statham', N'https://image.tmdb.org/t/p/w500/dIWDFAMfGdPCabkOvxaGCbFNWRF.jpg', N'https://image.tmdb.org/t/p/w1280/qWb7GjHHMBSHEp1gBbkGH5wRuSb.jpg', N'https://www.youtube.com/embed/Skpu5HaKkmw', N'https://www.youtube.com/embed/Skpu5HaKkmw', 1, 3, 1, 0, '2024-01-01'),
                    (48, N'Jurassic Park', 1993, 127, N'Durante uma visita prévia a um parque temático de dinossauros criados por engenharia genética, um sabotador desliga os sistemas de segurança e os dinossauros fogem e começam a caçar os visitantes.', N'Steven Spielberg', N'Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough', N'https://image.tmdb.org/t/p/w500/oU7Oq2kZm5cCGjRl3kfBnFXcjdA.jpg', N'https://image.tmdb.org/t/p/w1280/9BBTo108Kh4ROUNtSiVdNAZFCTa.jpg', N'https://www.youtube.com/embed/QWBKEmWWL38', N'https://www.youtube.com/embed/QWBKEmWWL38', 1, 3, 1, 0, '2024-01-01'),
                    (49, N'Vingadores: Guerra Infinita', 2018, 149, N'Os Vingadores e seus aliados devem estar dispostos a sacrificar tudo em uma tentativa de derrotar o poderoso Thanos, antes que sua blitz de devastação e ruína coloque um fim ao universo.', N'Anthony Russo, Joe Russo', N'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans', N'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', N'https://image.tmdb.org/t/p/w1280/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg', N'https://www.youtube.com/embed/6ZfuNTqbHE8', N'https://www.youtube.com/embed/6ZfuNTqbHE8', 1, 3, 1, 0, '2024-01-01'),
                    (50, N'Blade Runner 2049', 2017, 164, N'Um novo caçador de andróides (K) descobre um segredo há muito soterrado que tem o potencial de mergulhar o que resta da sociedade no caos. A descoberta de K o leva a uma busca por Rick Deckard, um antigo caçador que desapareceu há trinta anos.', N'Denis Villeneuve', N'Ryan Gosling, Harrison Ford, Ana de Armas, Sylvia Hoeks', N'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg', N'https://image.tmdb.org/t/p/w1280/ilRyazdMJwN3LBXF64ZFhqOCsYH.jpg', N'https://www.youtube.com/embed/gCcx85zbxz4', N'https://www.youtube.com/embed/gCcx85zbxz4', 4, 4, 1, 0, '2024-01-01');

                SET IDENTITY_INSERT Filmes OFF;
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
